language: php

branches:
  only:
    - master
    - dev

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --prefer-source

before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

script:
  - php phpcs.phar --standard=./phpcs.xml --encoding=utf-8 ./src
  - mkdir -p build/logs
  - vendor/bin/phpunit --debug --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
